apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: fiap-tasty
spec:
  replicas: 2
  serviceName: "postgres"
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-cm
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: init-db
              mountPath: /docker-entrypoint-initdb.d
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: init-db
          configMap:
            name: init-sql
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
